name: Test CF-Firewall

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          shellcheck cf-firewall.sh install.sh

  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["20.04", "22.04"]
        backend: ["iptables", "nftables"]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies for iptables
        if: matrix.backend == 'iptables'
        run: |
          sudo apt-get update
          sudo apt-get install -y iptables ipset curl

      - name: Install dependencies for nftables
        if: matrix.backend == 'nftables'
        run: |
          sudo apt-get update
          sudo apt-get install -y nftables curl
          sudo systemctl enable nftables
          sudo systemctl start nftables

      - name: Test installation
        run: |
          sudo cp cf-firewall.sh /usr/local/bin/cf-firewall
          sudo chmod +x /usr/local/bin/cf-firewall

      - name: Force backend selection
        run: |
          sudo mkdir -p /etc/cloudflare-firewall
          echo "${{ matrix.backend }}" | sudo tee /etc/cloudflare-firewall/firewall_mode

      - name: Test initialization
        run: |
          sudo cf-firewall init

      - name: Verify backend
        run: |
          sudo cf-firewall status | grep "Firewall Backend" | grep "${{ matrix.backend }}"

      - name: Test port management
        run: |
          sudo cf-firewall add-port 8080
          sudo cf-firewall list-ports | grep 8080
          sudo cf-firewall remove-port 8080

      - name: Test IP management
        run: |
          sudo cf-firewall add-ip 192.168.1.100
          sudo cf-firewall add-ip 2001:db8::1
          sudo cf-firewall list-ips
          sudo cf-firewall remove-ip 192.168.1.100
          sudo cf-firewall remove-ip 2001:db8::1

      - name: Test backend switching
        run: |
          if [ "${{ matrix.backend }}" = "iptables" ]; then
            sudo apt-get install -y nftables
            sudo cf-firewall switch-backend nftables
            sudo cf-firewall status | grep "Firewall Backend" | grep "nftables"
            sudo cf-firewall switch-backend iptables
            sudo cf-firewall status | grep "Firewall Backend" | grep "iptables"
          fi

      - name: Test status
        run: |
          sudo cf-firewall status

  test-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y iptables ipset curl sudo systemd

      - name: Test installation
        run: |
          cp cf-firewall.sh /usr/local/bin/cf-firewall
          chmod +x /usr/local/bin/cf-firewall

      - name: Test basic functionality
        run: |
          cf-firewall help

  test-rockylinux:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          dnf install -y iptables ipset curl

      - name: Test installation
        run: |
          cp cf-firewall.sh /usr/local/bin/cf-firewall
          chmod +x /usr/local/bin/cf-firewall

      - name: Test basic functionality
        run: |
          cf-firewall help
